version: '2'
services:
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"

  keycloak_proxy:
    image: quay.io/ukhomeofficedigital/go-keycloak-proxy:latest
    volumes:
      - ./data:/opt/data
    expose:
      - 9000
    ports:
      - "8081:8080"
    environment:
      PROXY_CONFIG_FILE: /opt/data/config.yml
      PROXY_CLIENT_ID: drt
      PROXY_CLIENT_SECRET: d3bec7f4-9a5f-4c5a-b03b-f4c6e69dbb63
  nginx:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    expose:
      - 9000
    environment:
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
